### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Ben3Ben3** [trevorld/Hanzi_Stats#2]
Hello, thank you for the awesome addon.
Unfortunately I am getting following error:

Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "\Anki\addons\Hanzi_Stats.py", line 5
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

can you help me?

**Comment by trevorld** [comment]
Could you give me more information?  It works fine (on my Linux laptops) in the current and recent versions of Anki.  Did it download corrupted?  When you open up the file in a decent text editor (i.e not Notepad) what is your line 5?  It should be a python comment which shouldn't throw any syntax errors.  When I run ``python Hanzi_Stats.py`` or ``python3 Hanzi_Stats.py`` in a terminal I'll get import errors but no syntax errors.

**Comment by Ben3Ben3** [comment]
Thank you very much for your fast reply. sorry for all the trouble. Installing Anki again did the trick. Its working now. Thanks!
One last questions:  Are the HSK Levels accurate? I am just wondering because they contain only a small amount of words compared to other lists (HSK 4 are 447 words, while on other site it is stated that HSK 4 contains about 1200 words). So whats the different?

**Comment by trevorld** [comment]
Glad that it works now.  This plugin shows you the new **characters** introduced in each HSK level.  It doesn't keep track of **words**.  The number of new characters is much smaller than the number of new words.  It is from the 2012 "New" HSK list (which is different from the 2010 New HSK list or any of the older original HSK lists).  I'm not aware of any newer lists being released but I may be wrong.  In this github repo you can see the exact list of words as well as the python program I used to derive the character list.

Since the problem seems to be solved I am closing this issue.

**Comment by trevorld** [comment]
Don't know what your desired behaviour is but just today I updated the code to show statistics for characters found only the first field instead of all fields.  This should now match the behaviour of the known character graphs in the Chinese support plugin.  If this behaviour sounds better to you should update otherwise keep what you have.  I've also just uploaded to anki addon website if you'd rather download using that:

https://ankiweb.net/shared/info/181243826

**Comment by Ben3Ben3** [comment]
thank you very much for your help and the explanation. I was just curious about the different numbers. Now I got it. Thank you very much! Great work!
