### ISSUE TITLE
Words_Stats

### ISSUE THREAD

**Issue by Dougwar** [trevorld/Hanzi_Stats#4]
Is there possible to made a Word_Stats for HSK, the addon search for a specific field and compare with a wordlist from every HSK level?
Thanks

**Comment by trevorld** [comment]
Should be theoretically possible but I'm personally not going to take the time to implement that since it'd be a non-trivial task that doesn't seem to add much particular value if you have already tagged your flashcards with HSK level and know how to use the Anki Browser.  I'd have to make non-trivial modifications to code I didn't originally write since the code builds up a set of characters not words.  Also, if you've tagged your words with HSK level (perhaps at the time of importing pre-made HSK flashcards) then it is very easy to manually get these statistics in  the browser i.e. divide:

    tag:hsk6 -is:suspended

by

    tag:hsk6

To know the percentage of HSK6 words you've learned.  You can create custom searches in "My Searches" to semi-automate this (i.e. do a search then click the heart).  For example I've created a custom search in "My Searches" called "hsk to learn" which automatically builds me a list of every HSK word I haven't tried to learn yet (i.e. not learned and not "leeched"): 

    tag:hsk* is:suspended prop:ivl=0

You could also build similar lists by level:

    tag:hsk6 is:suspended prop:ivl=0
